services:
- name: web
  envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: “Hive-Techware-Backend.settings.production”
  buildCommand: “python manage.py migrate && python manage.py collectstatic --noinput”
  startCommand: “gunicorn Hive-Techware-Backend.wsgi:application --bind 0.0.0.0:$PORT”
